//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Event_Diary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_photo
    {
        public string Name { get; set; }
        public byte[] photo { get; set; }
    }
}
